// <auto-generated />
namespace LEDE.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _83014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_83014));
        
        string IMigrationMetadata.Id
        {
            get { return "201408302207272_8-30-14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
