// <auto-generated />
namespace LEDE.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _01192016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01192016));
        
        string IMigrationMetadata.Id
        {
            get { return "201601192121527_01192016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
