// <auto-generated />
namespace ECSEL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class programcohortidremoval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(programcohortidremoval));
        
        string IMigrationMetadata.Id
        {
            get { return "201407310111062_programcohortidremoval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
