// <auto-generated />
namespace LEDE_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class allownull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allownull));
        
        string IMigrationMetadata.Id
        {
            get { return "201407100110027_allownull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
